Initial commit to data-binding
wildbiotiger/dotnet-intro-kstone pull request #1
Opened 2019-05-28 15:28 UTC by karlastone4

Is there any ways you can think to improve this program?

2019-05-28 15:38 UTC, wildbiotiger requested changes

2019-05-28 15:38 UTC, wildbiotiger commented on Pirates/Pirates/MainViewModel.cs
> +
remove extra whitespace

2019-05-28 15:38 UTC, wildbiotiger commented on Pirates/Pirates/MainViewModel.cs
> +   public class MainViewModel
add intellisense comments

2019-05-28 15:38 UTC, wildbiotiger commented on Pirates/Pirates/MainWindow.xaml.cs
> +﻿using System;
remove unused usings

2019-05-28 15:38 UTC, wildbiotiger commented on Pirates/Pirates/MainWindow.xaml.cs
> +
remove extra whitespace

2019-05-28 15:38 UTC, wildbiotiger commented on Pirates/Pirates/MainViewModel.cs
> +namespace Testing2
rename namespace in all files to something useful
see examples of C# namespace definitions on the web

2019-05-28 15:38 UTC, wildbiotiger commented on Pirates/Pirates/MainWindow.xaml.cs
> +
remove whitespace

2019-05-28 15:38 UTC, wildbiotiger commented on Pirates/Pirates/ViewModel/PirateNames.cs
> +    public class PirateNames
make this singular

2019-05-28 15:38 UTC, wildbiotiger commented on Pirates/Pirates/ViewModel/Pirates.cs
> +    class Pirates
make this singular

2019-05-28 15:38 UTC, wildbiotiger commented on VisualStudio.gitignore
> +## Ignore Visual Studio temporary files, build results, and
remove this file

2019-05-28 16:28 UTC, karlastone4 reviewed
Updated files

2019-05-28 18:15 UTC, wildbiotiger requested changes

2019-05-28 18:15 UTC, wildbiotiger commented on Pirates/Pirates/MainWindow.xaml.cs
> +        }
add single spacing between functions

2019-05-28 18:15 UTC, wildbiotiger commented on Pirates/Pirates/MainWindow.xaml.cs
> +        //adding the textbox info to pirates collection by clicking add button
dont use present progressive tense in comments
try "adds the textbox info..."

2019-05-28 18:15 UTC, wildbiotiger commented on Pirates/Pirates/ViewModel/MainViewModel.cs
> +    public class MainViewModel
needs comments

2019-05-28 18:15 UTC, wildbiotiger commented on Pirates/Pirates/ViewModel/Pirates.cs
> +namespace Pirate.ViewModel
needs comments

2019-05-28 18:18 UTC, wildbiotiger requested changes

2019-05-28 18:18 UTC, wildbiotiger commented on Pirates/Pirates/MainWindow.xaml
> +        <TextBox x:Name="TextBox" Grid.ColumnSpan="2" Margin="10,16,21,5" TextWrapping="Wrap" KeyDown="EnterAdd" KeyUp="EnterClear"/>
remove unused names
sort the attributes so that grid.XXX is first and margins are second
events and interaction should be last
space out the attributes on multiple lines so they dont go offscreen

2019-05-28 18:18 UTC, wildbiotiger commented on Pirates/Pirates/MainWindow.xaml.cs
> +        //add the textbox info to pirates collection by clicking add button
turn these into intellisense comments

2019-05-28 18:18 UTC, wildbiotiger commented on Pirates/Pirates/Pirate.cs
> +namespace Testing2.Directory
rename

2019-05-28 18:18 UTC, wildbiotiger commented on Pirates/Pirates/ViewModel/MainViewModel.cs
> +        //new method for shorthand adding pirate names from collection
convert to intellisense comments

2019-05-29 16:11 UTC, wildbiotiger requested changes

2019-05-29 16:11 UTC, wildbiotiger commented on Pirates/Pirates/MainWindow.xaml
> +        <ListBox Grid.ColumnSpan="2" Margin="10,10,10,16" Grid.Row="2" Grid.RowSpan="2" x:Name="ListBox"
move grid properties before margin

2019-05-29 16:11 UTC, wildbiotiger commented on Pirates/Pirates/MainWindow.xaml.cs
> +    /// class for Mainwindow code
make these intellisense comments, three slashes is not the same as the XML syntax intellisense produces

2019-05-29 16:11 UTC, wildbiotiger commented on Pirates/Pirates/ViewModel/Pirates.cs
>  namespace Pirate.ViewModel
the namespace does not need comments, make it above the class

2019-06-03 14:39 UTC, wildbiotiger requested changes

2019-06-03 14:39 UTC, wildbiotiger commented on .gitignore
> +Pirates/Pirates/ViewModel/BlackPearl.png
why are these being ignored?

2019-06-03 14:39 UTC, wildbiotiger commented on Pirates/Pirates/MainWindow.xaml
> +            <RowDefinition Height="60*" />
for both rows and cols, reduce the star parameters and use auto for everything else

2019-06-03 14:39 UTC, wildbiotiger commented on Pirates/Pirates/MainWindow.xaml
> +        <Label Grid.ColumnSpan="4" Grid.Row="7"  x:Name="PortBlock" Style="{StaticResource Displays}"/>
remove x:Names for the items that dont need it

2019-06-03 14:39 UTC, wildbiotiger commented on Pirates/Pirates/MainWindow.xaml.cs
>          ///add the textbox info to pirates collection by clicking add button
change this to a full intellisense comment - do this for all other comments

2019-06-03 14:39 UTC, wildbiotiger commented on Pirates/Pirates/ViewModel/MainViewModel.cs
> +        public void RemoveShip(int loseShip)
is this function removing a ship or a pirate? seems redundant

2019-06-03 17:41 UTC, wildbiotiger requested changes

2019-06-03 17:41 UTC, wildbiotiger commented on Pirates/Pirates/ViewModel/MainViewModel.cs
> +        public void AddPerson(string newPerson)
remove the addperson/ship/landing functions, those aren't quite what we need them to be. they don't accomplish what you think they do.

2019-06-03 21:48 UTC, wildbiotiger approved these changes

2019-06-03 21:49 UTC, merged